/**
 * UI strings. `&` marks the underlined access key in menus and buttons.
 * Czech wording follows the Czech edition of Windows 95 where one existed.
 */
export const en = {
  // Desktop
  'desktop.myComputer': 'My Computer',
  'desktop.outlook': 'Outlook Express',
  'desktop.ie': 'Internet Explorer',
  'desktop.arrangeIcons': 'Arrange &Icons',
  'desktop.byName': 'by &Name',
  'desktop.lineUp': 'Line &up Icons',
  'desktop.refresh': 'R&efresh',
  'desktop.properties': 'P&roperties',
  'desktop.open': '&Open',

  // Taskbar / tray
  'taskbar.start': 'Start',
  'taskbar.startHint': 'Click here to begin.',
  'taskbar.language': 'Language',
  'taskbar.langEn': '&English (United States)',
  'taskbar.langCs': '&Czech (Čeština)',

  // Start menu
  'start.programs': '&Programs',
  'start.documents': '&Documents',
  'start.settings': '&Settings',
  'start.find': '&Find',
  'start.findFiles': '&Files or Folders...',
  'start.help': '&Help',
  'start.github': '&GitHub',
  'start.shutdown': 'Sh&ut Down...',
  'start.startup': 'StartUp',
  'start.empty': '(Empty)',
  'start.controlPanel': '&Control Panel',
  'start.printers': '&Printers',
  'start.taskbar': '&Taskbar...',
  'start.language': '&Language',
  'start.msdos': 'MS-DOS Prompt',

  // Window chrome
  'win.restore': '&Restore',
  'win.move': '&Move',
  'win.size': '&Size',
  'win.minimize': 'Mi&nimize',
  'win.maximize': 'Ma&ximize',
  'win.close': '&Close',
  'win.closeShortcut': 'Alt+F4',
  'win.minimizeTip': 'Minimize',
  'win.maximizeTip': 'Maximize',
  'win.restoreTip': 'Restore',
  'win.closeTip': 'Close',

  // Common buttons & menus
  'btn.ok': 'OK',
  'btn.cancel': 'Cancel',
  'btn.yes': '&Yes',
  'btn.no': '&No',
  'btn.help': '&Help',
  'btn.close': 'Close',
  'menu.file': '&File',
  'menu.edit': '&Edit',
  'menu.view': '&View',
  'menu.go': '&Go',
  'menu.favorites': 'F&avorites',
  'menu.help': '&Help',
  'menu.tools': '&Tools',
  'menu.compose': '&Compose',
  'menu.insert': '&Insert',
  'menu.format': 'F&ormat',
  'menu.close': '&Close',
  'menu.open': '&Open',
  'menu.selectAll': 'Select &All',
  'menu.invertSelection': '&Invert Selection',
  'menu.largeIcons': 'Lar&ge Icons',
  'menu.smallIcons': 'S&mall Icons',
  'menu.list': '&List',
  'menu.details': '&Details',
  'menu.statusBar': 'Status &Bar',
  'menu.toolbar': '&Toolbar',
  'menu.about': '&About {brand}',
  'menu.helpTopics': '&Help Topics',
  'menu.cut': 'Cu&t',
  'menu.copy': '&Copy',
  'menu.paste': '&Paste',
  'menu.undo': '&Undo',
  'menu.send': '&Send Message',

  // My Computer
  'mycomp.title': 'My Computer',
  'mycomp.objects': '{n} object(s)',
  'mycomp.selected': '{n} object(s) selected',
  'mycomp.colName': 'Name',
  'mycomp.colType': 'Type',
  'mycomp.colDescription': 'Description',
  'mycomp.typeDemo': 'Application',
  'mycomp.typeLink': 'Internet Shortcut',

  // About
  'about.title': 'About {brand}',
  'about.text': '{brand}\nA portfolio by {owner}.\n\nBuilt with HTML, CSS and TypeScript.\nNo Flash required.',

  // Internet Explorer
  'ie.title': '{page} - Internet Explorer',
  'ie.back': 'Back',
  'ie.forward': 'Forward',
  'ie.stop': 'Stop',
  'ie.refresh': 'Refresh',
  'ie.home': 'Home',
  'ie.search': 'Search',
  'ie.favorites': 'Favorites',
  'ie.print': 'Print',
  'ie.mail': 'Mail',
  'ie.address': 'A&ddress',
  'ie.go': 'Go',
  'ie.done': 'Done',
  'ie.opening': 'Opening page {url}...',
  'ie.zone': 'Internet zone',
  'ie.localZone': 'My Computer',
  'ie.goBack': '&Back',
  'ie.goForward': '&Forward',
  'ie.goHome': '&Home Page',
  'ie.favGithub': 'My GitHub',
  'ie.newWindow': 'Open in new &Window',
  'ie.externalTitle': 'Leaving {brand}',
  'ie.externalText': 'The page {url} lives outside of this computer.',
  'ie.externalOpen': 'Open it in a new browser tab',
  'ie.notFoundTitle': 'The page cannot be displayed',
  'ie.notFoundText': 'The page you are looking for is currently unavailable. Check the address and try again.',
  'ie.iframeNote': 'If the page stays blank, it does not allow being shown inside another page.',

  // Outlook Express
  'oe.title': 'Outlook Express',
  'oe.compose': 'Compose Message',
  'oe.composeShort': 'Compose',
  'oe.reply': 'Reply to Author',
  'oe.replyAll': 'Reply to All',
  'oe.forward': 'Forward',
  'oe.sendReceive': 'Send and Receive',
  'oe.delete': 'Delete',
  'oe.addressBook': 'Address Book',
  'oe.folders': 'Folders',
  'oe.inbox': 'Inbox',
  'oe.outbox': 'Outbox',
  'oe.sent': 'Sent Items',
  'oe.deleted': 'Deleted Items',
  'oe.drafts': 'Drafts',
  'oe.colFrom': 'From',
  'oe.colTo': 'To',
  'oe.colSubject': 'Subject',
  'oe.colReceived': 'Received',
  'oe.colSent': 'Sent',
  'oe.noMessage': 'There is no message selected.',
  'oe.noItems': 'There are no items in this view.',
  'oe.messages': '{n} message(s), {unread} unread',
  'oe.welcomeSubject': 'Welcome! Let’s get in touch',
  'oe.welcomeBody':
    'Hi there!\n\nThanks for stopping by my little corner of the Internet.\n\nIf you have an idea, a job offer, a question about one of my projects or just want to say hello, click "Compose Message" in the toolbar above and send me a note. I read every message and will get back to you by e-mail.\n\nHave a nice day,\n{owner}',
  'oe.checking': 'Checking for new messages...',
  'oe.noNew': 'There are no new messages on the server.',
  'oe.sendReceiveTitle': 'Outlook Express',

  // Compose
  'compose.title': 'New Message',
  'compose.titleSubject': '{subject}',
  'compose.send': 'Send',
  'compose.cut': 'Cut',
  'compose.copy': 'Copy',
  'compose.paste': 'Paste',
  'compose.undo': 'Undo',
  'compose.check': 'Check',
  'compose.spelling': 'Spelling',
  'compose.attach': 'Attach',
  'compose.to': 'To:',
  'compose.from': 'From:',
  'compose.name': 'Name:',
  'compose.subject': 'Subject:',
  'compose.fromPlaceholder': 'your.e-mail@example.com',
  'compose.namePlaceholder': 'Your name (optional)',
  'compose.bodyPlaceholder': 'Write your message here...',
  'compose.noSubject': '(no subject)',
  'compose.sending': 'Sending message...',
  'compose.sent': 'Your message has been sent. Thank you!',
  'compose.errEmail': 'Please enter a valid e-mail address in the From field so I can reply to you.',
  'compose.errBody': 'The message is empty. Please write something before sending.',
  'compose.errNotConfigured':
    'Outlook Express could not connect to the mail server.\n\nThe mail server has not been configured yet. Please try again later.',
  'compose.errSend': 'The message could not be sent.\n\nServer response: {error}',
  'compose.errNetwork': 'The message could not be sent because the server could not be reached. Check your connection and try again.',
  'compose.saveChanges': 'Do you want to save changes to this message?',

  // Find
  'find.title': 'Find: All Files',
  'find.titleNamed': 'Find: Files named {name}',
  'find.tabName': 'Name & Location',
  'find.tabDate': 'Date Modified',
  'find.tabAdvanced': 'Advanced',
  'find.named': '&Named:',
  'find.lookIn': '&Look in:',
  'find.lookInValue': 'My Computer',
  'find.subfolders': 'Include &subfolders',
  'find.findNow': 'F&ind Now',
  'find.stop': 'Sto&p',
  'find.newSearch': 'Ne&w Search',
  'find.allFiles': '&All files',
  'find.findAllCreated': '&Find all files created or modified:',
  'find.ofType': 'Of &type:',
  'find.allTypes': 'All Files and Folders',
  'find.containing': '&Containing text:',
  'find.colName': 'Name',
  'find.colFolder': 'In Folder',
  'find.colType': 'Type',
  'find.found': '{n} file(s) found',
  'find.searching': 'Searching...',
  'find.typeApp': 'Application',
  'find.typePage': 'HTML Document',
  'find.typeShortcut': 'Internet Shortcut',
  'find.typeProject': 'Project',

  // Help
  'help.title': '{brand} Help',
  'help.topics': 'Help Topics',
  'help.contents': 'Contents',
  'help.intro': 'Click a topic, and then click Display.',
  'help.display': '&Display',
  'help.t1': 'Welcome to {brand}',
  'help.b1':
    'This website pretends to be a computer from 1995. Everything happens on this one page: double-click the icons on the desktop (or tap them on a phone) to open programs.',
  'help.t2': 'Working with windows',
  'help.b2':
    'Drag a window by its title bar and resize it from its edges. Use the buttons in the top-right corner to minimize, maximize or close it. Double-click a title bar to maximize. Minimized windows wait for you on the taskbar.',
  'help.t3': 'Finding your way around',
  'help.b3':
    'My Computer holds demos of my projects. Internet Explorer shows who I am. Outlook Express lets you send me a message. Use Start > Find to search the whole site.',
  'help.t4': 'Keyboard shortcuts',
  'help.b4':
    'Ctrl+Esc (or Alt+S) opens the Start menu. F10 or Alt with an underlined letter opens a window\'s menus. Arrow keys move between desktop icons, Enter opens them. Esc closes menus and dialogs. Tab moves between controls.',
  'help.t5': 'Changing the language',
  'help.b5': 'Click the language indicator next to the clock, or use Start > Settings > Language.',

  // Welcome
  'welcome.title': 'Welcome',
  'welcome.heading': 'Welcome to',
  'welcome.didYouKnow': 'Did you know...',
  'welcome.tip1': 'This whole site is a desktop. Double-click an icon to open it.',
  'welcome.tip1Touch': 'This whole site is a desktop. Tap an icon to open it.',
  'welcome.tip2': 'Internet Explorer on the desktop tells you who I am.',
  'welcome.tip3': 'You can write to me using Outlook Express.',
  'welcome.tip4': 'My Computer is where demos of my projects live.',
  'welcome.tip5': 'Start > Find searches everything on this computer.',
  'welcome.tip6': 'Press Ctrl+Esc (or Alt+S) to open the Start menu from the keyboard.',
  'welcome.tip7': 'Prefer Czech? Click the language indicator next to the clock.',
  'welcome.bio': '&About me',
  'welcome.contact': '&Contact me',
  'welcome.nextTip': '&Next Tip',
  'welcome.showNext': '&Show this Welcome Screen next time you start {brand}',

  // Shut down
  'shutdown.title': 'Shut Down {brand}',
  'shutdown.question': 'Are you sure you want to:',
  'shutdown.optShutdown': '&Shut down the computer?',
  'shutdown.optRestart': '&Restart the computer?',
  'shutdown.optDos': 'Restart the computer in &MS-DOS mode?',
  'shutdown.optLogoff': '&Close all programs and log on as a different user?',
  'shutdown.wait': 'Please wait while your computer shuts down.',
  'shutdown.safe': 'It’s now safe to turn off\nyour computer.',
  'shutdown.continue': 'Click anywhere to continue',
  'shutdown.restarting': '{brand} is restarting...',

  // Boot
  'boot.starting': 'Starting {brand}...',
  'boot.skip': 'Press any key or click to skip',

  // Message boxes
  'msg.notAvailable': 'This feature is not available in this version of {brand}.',
} as const;

export type StringKey = keyof typeof en;

export const cs: Record<StringKey, string> = {
  'desktop.myComputer': 'Tento počítač',
  'desktop.outlook': 'Outlook Express',
  'desktop.ie': 'Internet Explorer',
  'desktop.arrangeIcons': 'Uspořádat &ikony',
  'desktop.byName': 'Podle &názvu',
  'desktop.lineUp': '&Zarovnat ikony',
  'desktop.refresh': '&Aktualizovat',
  'desktop.properties': '&Vlastnosti',
  'desktop.open': '&Otevřít',

  'taskbar.start': 'Start',
  'taskbar.startHint': 'Začněte klepnutím sem.',
  'taskbar.language': 'Jazyk',
  'taskbar.langEn': '&Angličtina (English)',
  'taskbar.langCs': '&Čeština',

  'start.programs': '&Programy',
  'start.documents': '&Dokumenty',
  'start.settings': '&Nastavení',
  'start.find': 'Na&jít',
  'start.findFiles': '&Soubory či složky...',
  'start.help': 'Náp&ověda',
  'start.github': '&GitHub',
  'start.shutdown': '&Vypnout...',
  'start.startup': 'Po spuštění',
  'start.empty': '(Prázdné)',
  'start.controlPanel': '&Ovládací panely',
  'start.printers': '&Tiskárny',
  'start.taskbar': '&Hlavní panel...',
  'start.language': '&Jazyk',
  'start.msdos': 'Příkazový řádek MS-DOS',

  'win.restore': '&Obnovit',
  'win.move': '&Přesunout',
  'win.size': '&Velikost',
  'win.minimize': '&Minimalizovat',
  'win.maximize': 'Ma&ximalizovat',
  'win.close': '&Zavřít',
  'win.closeShortcut': 'Alt+F4',
  'win.minimizeTip': 'Minimalizovat',
  'win.maximizeTip': 'Maximalizovat',
  'win.restoreTip': 'Obnovit',
  'win.closeTip': 'Zavřít',

  'btn.ok': 'OK',
  'btn.cancel': 'Storno',
  'btn.yes': '&Ano',
  'btn.no': '&Ne',
  'btn.help': 'Náp&ověda',
  'btn.close': 'Zavřít',
  'menu.file': '&Soubor',
  'menu.edit': 'Úpr&avy',
  'menu.view': '&Zobrazit',
  'menu.go': '&Přejít',
  'menu.favorites': '&Oblíbené',
  'menu.help': '&Nápověda',
  'menu.tools': 'Nás&troje',
  'menu.compose': '&Vytvořit',
  'menu.insert': '&Vložit',
  'menu.format': '&Formát',
  'menu.close': '&Zavřít',
  'menu.open': '&Otevřít',
  'menu.selectAll': 'Vy&brat vše',
  'menu.invertSelection': '&Invertovat výběr',
  'menu.largeIcons': '&Velké ikony',
  'menu.smallIcons': '&Malé ikony',
  'menu.list': '&Seznam',
  'menu.details': '&Podrobnosti',
  'menu.statusBar': 'Stavový &řádek',
  'menu.toolbar': 'Panel &nástrojů',
  'menu.about': '&O systému {brand}',
  'menu.helpTopics': '&Témata nápovědy',
  'menu.cut': '&Vyjmout',
  'menu.copy': '&Kopírovat',
  'menu.paste': 'V&ložit',
  'menu.undo': '&Zpět',
  'menu.send': '&Odeslat zprávu',

  'mycomp.title': 'Tento počítač',
  'mycomp.objects': 'Objektů: {n}',
  'mycomp.selected': 'Vybráno objektů: {n}',
  'mycomp.colName': 'Název',
  'mycomp.colType': 'Typ',
  'mycomp.colDescription': 'Popis',
  'mycomp.typeDemo': 'Aplikace',
  'mycomp.typeLink': 'Zástupce Internetu',

  'about.title': 'O systému {brand}',
  'about.text': '{brand}\nPortfolio, které vytvořil {owner}.\n\nPostaveno na HTML, CSS a TypeScriptu.\nFlash není potřeba.',

  'ie.title': '{page} - Internet Explorer',
  'ie.back': 'Zpět',
  'ie.forward': 'Vpřed',
  'ie.stop': 'Zastavit',
  'ie.refresh': 'Obnovit',
  'ie.home': 'Domů',
  'ie.search': 'Hledat',
  'ie.favorites': 'Oblíbené',
  'ie.print': 'Tisk',
  'ie.mail': 'Pošta',
  'ie.address': '&Adresa',
  'ie.go': 'Přejít',
  'ie.done': 'Hotovo',
  'ie.opening': 'Otevírání stránky {url}...',
  'ie.zone': 'Zóna Internet',
  'ie.localZone': 'Tento počítač',
  'ie.goBack': '&Zpět',
  'ie.goForward': '&Vpřed',
  'ie.goHome': '&Domovská stránka',
  'ie.favGithub': 'Můj GitHub',
  'ie.newWindow': 'Otevřít v novém &okně',
  'ie.externalTitle': 'Opouštíte {brand}',
  'ie.externalText': 'Stránka {url} se nachází mimo tento počítač.',
  'ie.externalOpen': 'Otevřít ji na nové kartě prohlížeče',
  'ie.notFoundTitle': 'Stránku nelze zobrazit',
  'ie.notFoundText': 'Hledaná stránka momentálně není k dispozici. Zkontrolujte adresu a zkuste to znovu.',
  'ie.iframeNote': 'Pokud stránka zůstane prázdná, nepovoluje zobrazení uvnitř jiné stránky.',

  'oe.title': 'Outlook Express',
  'oe.compose': 'Vytvořit zprávu',
  'oe.composeShort': 'Vytvořit',
  'oe.reply': 'Odpovědět autorovi',
  'oe.replyAll': 'Odpovědět všem',
  'oe.forward': 'Předat dál',
  'oe.sendReceive': 'Odeslat a přijmout',
  'oe.delete': 'Odstranit',
  'oe.addressBook': 'Adresář',
  'oe.folders': 'Složky',
  'oe.inbox': 'Doručená pošta',
  'oe.outbox': 'Pošta k odeslání',
  'oe.sent': 'Odeslaná pošta',
  'oe.deleted': 'Odstraněná pošta',
  'oe.drafts': 'Koncepty',
  'oe.colFrom': 'Od',
  'oe.colTo': 'Komu',
  'oe.colSubject': 'Předmět',
  'oe.colReceived': 'Přijato',
  'oe.colSent': 'Odesláno',
  'oe.noMessage': 'Není vybrána žádná zpráva.',
  'oe.noItems': 'V tomto zobrazení nejsou žádné položky.',
  'oe.messages': 'Zpráv: {n}, nepřečtených: {unread}',
  'oe.welcomeSubject': 'Vítejte! Ozvěte se mi',
  'oe.welcomeBody':
    'Ahoj!\n\nDíky, že ses zastavil(a) v mém malém koutku Internetu.\n\nPokud máš nápad, pracovní nabídku, dotaz k některému z mých projektů nebo mě chceš jen pozdravit, klikni nahoře na „Vytvořit zprávu“ a pošli mi pár řádků. Čtu každou zprávu a odpovím e-mailem.\n\nMěj se hezky,\n{owner}',
  'oe.checking': 'Probíhá kontrola nových zpráv...',
  'oe.noNew': 'Na serveru nejsou žádné nové zprávy.',
  'oe.sendReceiveTitle': 'Outlook Express',

  'compose.title': 'Nová zpráva',
  'compose.titleSubject': '{subject}',
  'compose.send': 'Odeslat',
  'compose.cut': 'Vyjmout',
  'compose.copy': 'Kopírovat',
  'compose.paste': 'Vložit',
  'compose.undo': 'Zpět',
  'compose.check': 'Kontrola',
  'compose.spelling': 'Pravopis',
  'compose.attach': 'Příloha',
  'compose.to': 'Komu:',
  'compose.from': 'Od:',
  'compose.name': 'Jméno:',
  'compose.subject': 'Předmět:',
  'compose.fromPlaceholder': 'vas.e-mail@example.com',
  'compose.namePlaceholder': 'Vaše jméno (nepovinné)',
  'compose.bodyPlaceholder': 'Sem napište svou zprávu...',
  'compose.noSubject': '(bez předmětu)',
  'compose.sending': 'Odesílání zprávy...',
  'compose.sent': 'Zpráva byla odeslána. Děkuji!',
  'compose.errEmail': 'Do pole Od zadejte platnou e-mailovou adresu, abych vám mohl odpovědět.',
  'compose.errBody': 'Zpráva je prázdná. Před odesláním prosím něco napište.',
  'compose.errNotConfigured':
    'Aplikaci Outlook Express se nepodařilo připojit k poštovnímu serveru.\n\nPoštovní server zatím není nastaven. Zkuste to prosím později.',
  'compose.errSend': 'Zprávu nelze odeslat.\n\nOdpověď serveru: {error}',
  'compose.errNetwork': 'Zprávu nelze odeslat, protože server není dostupný. Zkontrolujte připojení a zkuste to znovu.',
  'compose.saveChanges': 'Chcete uložit změny této zprávy?',

  'find.title': 'Najít: Všechny soubory',
  'find.titleNamed': 'Najít: Soubory s názvem {name}',
  'find.tabName': 'Název a umístění',
  'find.tabDate': 'Datum změny',
  'find.tabAdvanced': 'Upřesnit',
  'find.named': '&Název:',
  'find.lookIn': '&Oblast hledání:',
  'find.lookInValue': 'Tento počítač',
  'find.subfolders': 'Včetně &podsložek',
  'find.findNow': 'Na&jít',
  'find.stop': '&Zastavit',
  'find.newSearch': 'Nové &hledání',
  'find.allFiles': '&Všechny soubory',
  'find.findAllCreated': '&Najít soubory vytvořené či změněné:',
  'find.ofType': '&Typ:',
  'find.allTypes': 'Všechny soubory a složky',
  'find.containing': '&Obsahující text:',
  'find.colName': 'Název',
  'find.colFolder': 'Ve složce',
  'find.colType': 'Typ',
  'find.found': 'Nalezeno souborů: {n}',
  'find.searching': 'Probíhá hledání...',
  'find.typeApp': 'Aplikace',
  'find.typePage': 'Dokument HTML',
  'find.typeShortcut': 'Zástupce Internetu',
  'find.typeProject': 'Projekt',

  'help.title': 'Nápověda systému {brand}',
  'help.topics': 'Témata nápovědy',
  'help.contents': 'Obsah',
  'help.intro': 'Klepněte na téma a potom na tlačítko Zobrazit.',
  'help.display': '&Zobrazit',
  'help.t1': 'Vítejte v systému {brand}',
  'help.b1':
    'Tento web předstírá, že je počítač z roku 1995. Všechno se odehrává na jedné stránce: programy otevřete poklepáním na ikony na ploše (na telefonu klepnutím).',
  'help.t2': 'Práce s okny',
  'help.b2':
    'Okno přesunete tažením za záhlaví a jeho velikost změníte tažením za okraj. Tlačítky v pravém horním rohu okno minimalizujete, maximalizujete nebo zavřete. Poklepáním na záhlaví okno maximalizujete. Minimalizovaná okna na vás počkají na hlavním panelu.',
  'help.t3': 'Jak se tu vyznat',
  'help.b3':
    'Ve složce Tento počítač najdete ukázky mých projektů. Internet Explorer vám řekne, kdo jsem. Přes Outlook Express mi můžete napsat. Příkazem Start > Najít prohledáte celý web.',
  'help.t4': 'Klávesové zkratky',
  'help.b4':
    'Ctrl+Esc (nebo Alt+S) otevře nabídku Start. F10 nebo Alt s podtrženým písmenem otevře nabídky okna. Šipkami se pohybujete mezi ikonami na ploše, klávesou Enter je otevřete. Esc zavírá nabídky a dialogy. Tabulátor přechází mezi ovládacími prvky.',
  'help.t5': 'Změna jazyka',
  'help.b5': 'Klepněte na indikátor jazyka vedle hodin nebo použijte Start > Nastavení > Jazyk.',

  'welcome.title': 'Vítejte',
  'welcome.heading': 'Vítejte v systému',
  'welcome.didYouKnow': 'Víte, že...',
  'welcome.tip1': 'Celý tento web je pracovní plocha. Ikonu otevřete poklepáním.',
  'welcome.tip1Touch': 'Celý tento web je pracovní plocha. Ikonu otevřete klepnutím.',
  'welcome.tip2': 'Internet Explorer na ploše vám prozradí, kdo jsem.',
  'welcome.tip3': 'Napsat mi můžete přes Outlook Express.',
  'welcome.tip4': 'Ve složce Tento počítač bydlí ukázky mých projektů.',
  'welcome.tip5': 'Start > Najít prohledá celý tento počítač.',
  'welcome.tip6': 'Klávesami Ctrl+Esc (nebo Alt+S) otevřete nabídku Start z klávesnice.',
  'welcome.tip7': 'Radši anglicky? Klepněte na indikátor jazyka vedle hodin.',
  'welcome.bio': '&O mně',
  'welcome.contact': '&Napište mi',
  'welcome.nextTip': '&Další tip',
  'welcome.showNext': '&Zobrazit tuto uvítací obrazovku při příštím spuštění systému {brand}',

  'shutdown.title': 'Vypnout systém {brand}',
  'shutdown.question': 'Opravdu chcete:',
  'shutdown.optShutdown': '&Vypnout počítač?',
  'shutdown.optRestart': '&Restartovat počítač?',
  'shutdown.optDos': 'Restartovat počítač v režimu &MS-DOS?',
  'shutdown.optLogoff': '&Zavřít všechny programy a přihlásit se jako jiný uživatel?',
  'shutdown.wait': 'Počkejte prosím, probíhá vypínání počítače.',
  'shutdown.safe': 'Nyní můžete počítač\nbezpečně vypnout.',
  'shutdown.continue': 'Pokračujte klepnutím kamkoli',
  'shutdown.restarting': 'Probíhá restart systému {brand}...',

  'boot.starting': 'Spouštění systému {brand}...',
  'boot.skip': 'Přeskočíte stiskem klávesy nebo klepnutím',

  'msg.notAvailable': 'Tato funkce není v této verzi systému {brand} k dispozici.',
};
